syntax = "proto3";

package pb;

option go_package = "./pb";

message MessageRequest{
  string seq = 1;
  string cmd = 2;
  bytes data = 3;
}

message MessageResponse{
  string seq = 1;
  string cmd = 2;
  Response response = 3;
}

message Response{
  int32 code = 1;
  string msg = 2;
  bytes data = 3;
}

message HeartbeatReq {
  string user_id = 1;
}

message HeartbeatResp {

}

message PingReq {
  string msg = 1;
}

message PingResp {
  string msg = 1;
}

message LoginReq {
  string user_id = 1;
  string app_id = 2;
  string token = 3;
}

message LoginResp {

}