// Code generated by "stringer -type Code -linecomment"; DO NOT EDIT.

package e

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[OKCode-0]
	_ = x[BadRequestCode - -1]
	_ = x[SystemErrorCode - -2]
	_ = x[ParseErrorCode - -3]
	_ = x[NotFoundRouteCode-4001]
}

const (
	_Code_name_0 = "Parse ErrorSystem ErrorServer ErrorOK"
	_Code_name_1 = "Not Found Route"
)

var (
	_Code_index_0 = [...]uint8{0, 11, 23, 35, 37}
)

func (i Code) String() string {
	switch {
	case -3 <= i && i <= 0:
		i -= -3
		return _Code_name_0[_Code_index_0[i]:_Code_index_0[i+1]]
	case i == 4001:
		return _Code_name_1
	default:
		return "Code(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
