// Code generated by "stringer -type Code -linecomment"; DO NOT EDIT.

package e

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[OKCode-0]
	_ = x[BadRequestCode - -1]
	_ = x[SystemErrorCode - -2]
	_ = x[ParseErrorCode-1]
	_ = x[NotLoggedInCode-1000]
	_ = x[NotFoundRouteCode-4001]
}

const (
	_Code_name_0 = "System ErrorServer ErrorOKParse Error"
	_Code_name_1 = "Not Logged In"
	_Code_name_2 = "Not Found Route"
)

var (
	_Code_index_0 = [...]uint8{0, 12, 24, 26, 37}
)

func (i Code) String() string {
	switch {
	case -2 <= i && i <= 1:
		i -= -2
		return _Code_name_0[_Code_index_0[i]:_Code_index_0[i+1]]
	case i == 1000:
		return _Code_name_1
	case i == 4001:
		return _Code_name_2
	default:
		return "Code(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
