Name: app
Host: 0.0.0.0
Port: 8888
Verbose: true
Mode: dev
MsgType: proto

TokenConf:
  AccessSecret: ydgame_secret
  AccessExpire: 604800
  RefreshSecret: ydgame
  RefreshExpire: 2592000
  RefreshAfter: 604800

Log:
  ServiceName: "websocket_demo"
  Mode: "console"
  Encoding: "plain"
  Path: "logs"
  Level: "info"
  Stat: false

RedisConf:
  Host: "127.0.0.1:6379"
  Pass: "123456"

MysqlConf:
  DataSource: root:yd123456@tcp(47.120.79.159:3306)/badouye?charset=utf8mb4&parseTime=True&loc=Local
  MaxIdleConns: 10
  MaxOpenConns: 100
  MaxLifetime: 3600s
  SlowThreshold: 500ms